### ISSUE TITLE
why do the http and https versions of the site look very different?

### ISSUE THREAD

**Issue by s-ankur** [FlashpointProject/Flashpoint-Website#1]
![image](https://user-images.githubusercontent.com/33252312/71446504-15801480-274a-11ea-9f7e-505f354105f2.png)
vs
![image](https://user-images.githubusercontent.com/33252312/71446479-d8b41d80-2749-11ea-8e6a-f5ad7640873e.png)

**Comment by TBubba** [comment]
The site was recently updated from the image at the top to the one at the bottom.
The site looks like the new version when I connect with either ``http`` or ``https``.
My guess is that the old version was cached on the server or on your machine.
Try connecting again and see if it persists. If it does you can try pressing ``CTRL + F5`` to refresh the page and ignore the cache.

**Comment by s-ankur** [comment]
yes that seems to be the issue. resolved now
