### ISSUE TITLE
translations of the live website are broken

### ISSUE THREAD

**Issue by deluxghost** [FlashpointProject/Flashpoint-Website#36]
the website is using translations from `master` branch, which are very outdated.

translations have different placeholders from English, therefore the result strings are broken

there was also Czech option and this is also reverted

there are still `BlueMaxima`s on the home page

@colin969 @WumboSpasm

**Comment by ShadyMedic** [comment]
I'm not sure what's happening, I'm uploading the localisation files through FTP right after I download them directly from Crowdin, which I do whenever I recieve an e-mail that translation to a given language has been completed/verified.

**Comment by deluxghost** [comment]
maybe someone have replaced everything by master branch files

**Comment by ShadyMedic** [comment]
Possible.

Wumbo, are you deploying the localisation files automatically from GitHub, by any chance?

**Comment by WumboSpasm** [comment]
I'm not too knowledgeable of how the translation system works, but the most active translation branch is 29 commits behind master, so I imagine people on Crowdin are only seeing the outdated text. I'll have to talk to Colin about it on Discord.

**Comment by ShadyMedic** [comment]
Lately, I've been getting a lot of e-mails stating that translation to a given language was completed, followed by the same e-mail a few days later. That means, that translations necessary for the recent Flashpoint update were being added to Crowding in some way, most likely manually.

I'm not a Crowdin expert, but I think that it doesn't see or care about translation files here on GitHub. It just puts stuff here, not take it. New translations are added to Crowdin manually and independently of GitHub, as far as I know.

**Comment by WumboSpasm** [comment]
Turns out there was a misunderstanding on my part - Crowdin users are indeed seeing the latest English translation and I'm expected to fetch the translations on my own. I just need to figure out why Colin's tool to automate the process won't work.

**Comment by deluxghost** [comment]
there might be too many translation commits, if that's not expected, a script pushing translation to the webserver + english only repo should also work.

**Comment by ShadyMedic** [comment]
Honestly, I think that the way the system works now is alright. At least there are now not duplicate translations in different folders and devs can add new strings to translate before merging everything into master.

**Comment by ShadyMedic** [comment]
Okay, so just to clarify the issue, in case somebody stumbles on this again:

New string are needed
→ Somebody adds the new strings into `locales/en-US/___.json` files
→ This change is merged into master
→ Crowdin automatically fetches these strings and prompts the translators that new work is available
→ Translators translate, proofreaders proofread
→ I get an e-mail from Crowdin that a translation or verification of a given language was completed
→ I download the translated strings for the given language
→ I commit the updated files to the `shady-translations-updates` branch
→ I create a merge request from this branch into `master`
→ I merge it
→ Somebody with access to the website administration deploys the master to the webserver (if they remember...)
→ Strings on the website are now translated
