### ISSUE TITLE
The French and Czech translations of the homepage each have a broken "Download Flashpoint" graphic

### ISSUE THREAD

**Issue by VCheesey** [FlashpointProject/Flashpoint-Website#45]
![image](https://github.com/FlashpointProject/Flashpoint-Website/assets/38865196/9e0598b2-1e59-46ad-a5d9-af6b2a6216db)
Looks like they're calling for translated versions of the graphic that aren't actually on our servers.

**Comment by ShadyMedic** [comment]
Hi there, thank you for reporting this. I just submitted a fix in #47, let's hoppe it'll me merged and deployed soon.
